config/routes.rb
ResourceMang1::Application.routes.draw do
  resources :users do
    member do
      get 'skills'
      post 'add_skills'
      get 'profile'
      get 'dashboard'
      get 'similar_skill'
      post 'user_search'
    end
    collection do
      post 'search'
    end
  end
  
  resources :skills
  resources :session do 
    collection do 
      get 'logout'
    end
  end

  resources :categories

  root :to => 'session#new'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :skills
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :emp_id, :name, :email, :title
  has_many :skill_sets
  has_many :skills, :through => :skill_sets
  
  USER_ATTRIBUTES = ["l", "title", "description", "physicaldeliveryofficename", "givenname", "whencreated", 
                     "displayname", "department", "company", "streetaddress", "name", "samaccountname",
                     "mail", "manager", "mobile"]
  
  
  def self.update_or_create_user_info(user_info)
    user = find_by_email(user_info[:mail])
    if !user.blank?
      #todo update user with latest login info
      return user
    else
      user = User.create(:email => user_info[:mail], :name => user_info[:givenname], :emp_id =>  user_info[:samaccountname], :title => user_info[:title])      
      if user
        return user 
      else
        return ""  
      end
    end    
  end

  def skills_list(size=0)
    list = []
    skills.each{|s| list << s.name}
    list= list.size < size ? list :  list[0..size]
    return list.join(",") unless list.empty?
    "No skills added"
  end
  
  def skill_level(skill)
    skill_level = skill_sets.find_by_skill_id(skill.id)
    skill_level.blank? ? 1 :  skill_level
  end
  
  def skillset_last_updated_on
    return "" if skill_sets.empty?
    return skill_sets.first.created_at.strftime("%m/%d/%y")
  end
  
  def similar_skill_users(skill=nil)
    if skill
      skill_ids = skills.where("skills.id = #{skill.id}").map(&:id)
    else
      skill_ids = skills.map(&:id)
    end
    if skill_ids.size == 1
      User.joins(:skill_sets).where("skill_sets.skill_id = #{skill_ids[0]} and users.id != #{self.id}").group("users.id").includes(:skill_sets) 
    else
      User.joins(:skill_sets).where("skill_sets.skill_id in (#{skill_ids.join(',')}) and users.id != #{self.id}").group("users.id").includes(:skill_sets)   
    end
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  before_filter :authenticate_user
  custom_actions :resource => :skills
  
  def dashboard
    @user = User.find(params[:id]) 
    @users = @user.similar_skill_users
  end
  
  def similar_skill
    @skill = Skill.find(params[:skill])
    @user = User.find(params[:id]) 
    @users = @user.similar_skill_users(@skill)
    render :dashboard  
  end
  
  def user_search
    @user = User.find(params[:id])
    if !params[:search].blank?
      @users = User.includes(:skills).where("skills.name like '%#{params[:search]}%' or users.name like '%#{params[:search]}%' or users.emp_id = '#{params[:search]}'" )
    else
      @users = @user.similar_skill_users
    end  
    render :dashboard
  end

  def skills
    @user = User.find(params[:id])
    @skill_set = SkillSet.new
  end
  
  def add_skills
    @user = User.find(params[:id])
    SkillSet.transaction do
      skill_sets = @user.skill_sets.map(&:id)
      SkillSet.where(:id => skill_sets).destroy_all
      unless params[:skill_ids].nil?
        params[:skill_ids].each_with_index do |skill,i|
          SkillSet.create(:user_id => @user.id, :skill_id => skill.to_i, :level => params[:level_ids][i] )  
        end
      end
    end
    flash[:notice] = "Skill successfully added"
    redirect_to profile_user_path(@user)
  end
  
  
  def search
    if !params[:search].blank?
      @users = User.includes(:skills).where("skills.name like '%#{params[:search]}%'")
    else
      @users = User.all
    end  
    render :index
  end
  
  def profile
    

    if !params[:id].blank? 
      @user = User.find(params[:id])
      if !@user.blank?
        emp_id = "#{@user.emp_id}"
      else
        emp_id = params[:id]    
      end
      ldap = Net::LDAP.new :host => '10.237.5.106',
      :port => 3268,
      :auth => {
        :method => :simple,
        :username => "systompun",
        :password => "password-1"
      }
       
      if !params[:view].blank?
        filter = Net::LDAP::Filter.eq("cn", params[:view])         
      else
        filter = Net::LDAP::Filter.eq("sAMAccountName", emp_id)
      end

      @user_details = Hash.new
      treebase = "dc=cts,dc=com"
      ldap.search(:base => treebase, :filter => filter) do |entry|
        entry.each do |attribute, values|
          values.each do |value|
            @user_details[attribute.to_sym] = value
          end
        end
      end
    end
    
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def user_has_skill(user, skill)
    skill_ids = user.skills.map(&:id)
    return false,1 if skill_ids.empty?
    return false,1 if !skill_ids.include?(skill.id.to_i)  
    return true, user.skill_level(skill)
  end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, :readonly => true
  .field
    = f.label :email
    = f.number_field :email, :readonly => true
  .actions
    = f.submit 'Save', :class => "btn btn-primary"

app/views/users/dashboard.html.haml
.row
  .span12.text-center
    %h3 Welcome to Skill Management System 
%br
%br    
.row
  .span4  
    %h4
      Search users with similar skills : 
  .span6    
    = form_tag(:action => :user_search ) do
      .row
        .span3
          .form-group
            = text_field_tag :search, params[:search], :placeholder => "HTML, CSS ...."
        .span3    
          .form-group  
            = button_tag :class => "btn btn-primary"  do
              %i.icon-search
                Search
%br 
.row
  .span3.text-left
    %h4 List of users with skills :
  .span4.text-left
    %ul.nav.nav-pills
      - if params[:action] == 'dashboard'
        - @user.skills.each do |skill|
          %li.active{:style => "padding-bottom:2px;padding-top:2px;"}
            = link_to("#{skill.name}", similar_skill_user_path(:skill => skill.id), :style => "line-height: 7px;",:class => "skill-level-#{@user.skill_level(skill).level}")       
      - elsif !params[:skill].blank?         
        %li.active{:style => "padding-bottom:2px;padding-top:2px;"}
          = link_to("#{@skill.name}", similar_skill_user_path(:skill => @skill.id), :style => "line-height: 7px;",:class => "skill-level-#{@user.skill_level(@skill).level}")        
   
- if @users.blank?
  .row
    .span6.text-left
      - if params[:action] == 'dashboard'
        You have not updated any skills to your profile.
      - else
        No results found for your search.   
       
- else    
  %table.table.table-striped
    %thead
      %tr
        %th.span3 Name(Emp ID)
        %th.span9 Skills
        %th Last updated
        %th
    %tbody
    - @users.each do |user|
      %tr
        %td= link_to "#{user.name} (#{user.emp_id})", profile_user_path(user)
        %td
          %ul.nav.nav-pills
            - user.skills.each_with_index do |skill,i|
              - if i == 14 then
                - break
              %li.active{:style => "padding-bottom:2px;padding-top:2px;"}
                = link_to("#{skill.name}", '#', :style => "line-height: 7px;",:class => "skill-level-#{user.skill_level(skill).level}")
        %td= user.skillset_last_updated_on


%br                

app/views/users/edit.html.haml
%h3 Edit user

= render 'form'

app/views/users/index.html.haml
.row
  .span4
    %h3 Listing users
  .span6.pull-right
    .span4
      .row
        .span3
          .h2
            %b.skill-level-1
              1 - No working knowledge
    .span4
      .row
        .span3
          .h2
            %b.skill-level-2
              2 - Worked, but not extensively
    .span4
      .row
        .span3
          .h2
            %b.skill-level-3
              3 - Have working knowledge  
    .span4
      .row
        .span3
          .h2
            %b.skill-level-4
              4 - Extensive Working Knowledge
    
      .row
        .span3
          .h2
            %b.skill-level-5
              5 - Expert/Specialist  
%br
%br
  
%div
  = form_tag(:action => :search ) do
    .form-group
      = text_field_tag :search, "", :placeholder => "HTML, CSS ...."
    .form-group  
      = button_tag :class => "btn btn-primary"  do
        %i.icon-search
          Search
%table.table.table-striped
  %thead
    %tr
      %th Name(Emp ID)
      %th.span7 Skills
      %th Last updated
      %th
  %tbody
  - @users.each do |user|
    %tr
      %td= link_to "#{user.name} (#{user.emp_id})", profile_user_path(user)
      %td
        %ul.nav.nav-pills
          - user.skills.each_with_index do |skill,i|
            - if i == 14 then
              - break
            %li.active{:style => "padding-bottom:2px;padding-top:2px;"}
              = link_to("#{skill.name}", skill_path(skill.id), :style => "line-height: 7px;",:class => "skill-level-#{user.skill_level(skill).level}")
      %td= user.skillset_last_updated_on
      %td
        = link_to profile_user_path(user) do
          %i.icon-eye-open
          Show
      %td
        = link_to edit_user_path(user) do
          %i.icon-pencil
          Edit
          

      %td
        = link_to user, :method => :delete, :data => { :confirm => 'Are you sure?' } do
          %i.icon-trash
          Delete
      %td
        = link_to skills_user_path(user) do
          %i.icon-plus
          Update Skills

%br

=# link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/profile.html.haml
.span7
  .row
    .span3
      .h2
        %b Profile Information
  %br
  %br 
  .row
    .span1
      %i
        Contact   
    .span2
      %b
        Alias
    .span4.text-primary
      = @user_details[:samaccountname]
  .row
    .span1
      %br
    .span2
      %b
        E-mail
    .span4     
      = @user_details[:mail]
  .row
    .span1
      %br
    .span2
      %b
        Office
    .span4     
      = @user_details[:physicaldeliveryofficename] 
  
  %br
  %br    
  .row
    .span1
      %i
        Information   
    .span2
      %b
        Job title
    .span4.text-primary
      = @user_details[:title]
  .row
    .span1
      %br
    .span2
      %b
        Department
    .span4     
      = @user_details[:department]
  .row
    .span1
      %br
    .span2
      %b
        Company
    .span4     
      = @user_details[:company]   
      
  .row
    .span1
      %br
    .span2
      %b
        Manager
    .span4   
      - name = @user_details[:manager].split(",")[0].split("=")[1] if !@user_details[:manager].blank?
      = name
      =# link_to name, profile_user_path(:view => name)
  
  %br
  %br
  .row
    .span4
      %i
        Address (Mailing Address)
  .row
    .span1
      %br        
    .span2
      %b
        Street
    .span4.text-primary{:style=>"overflow:hidden;"}
      = @user_details[:streetaddress]
  .row
    .span1
      %br
    .span2
      %b
        City
    .span4     
      = @user_details[:l]
  .row
    .span1
      %br
    .span2
      %b
        State/Province
    .span4     
      = @user_details[:st]   
      
  .row
    .span1
      %br
    .span2
      %b
        Postal code
    .span4     
      = @user_details[:postalcode]
  
  .row
    .span1
      %br
    .span2
      %b
        Country/Region
    .span4     
      = @user_details[:co]
.span4
  .row
    .span3
      .h2
        %b 
          Expected Proficiency

.span4
  .row
    .span3
      .h2
        %b.skill-level-1 
          1- No working knowledge
.span4
  .row
    .span3
      .h2
        %b.skill-level-2
          2 -Worked, but not extensively
.span4
  .row
    .span3
      .h2
        %b.skill-level-3
          3 - Have working knowledge  
.span4
  .row
    .span3
      .h2
        %b.skill-level-4
          4 - Extensive Working Knowledge

  .row
    .span3
      .h2
        %b.skill-level-5
          5 - Expert/Specialist
  %br
  %br
  
.span4
  .row
    .span3
      .h2
        %b 
          Skills
          - if !@user.skillset_last_updated_on.empty?
            = "( Last updated on : #{@user.skillset_last_updated_on} )"
     
  .row      
    .span3
      - if @user.skills.empty?
        No skills added to this profile. Click on 
        %b
          Update Skills
        link to update skill set.
      - else 
        %ul.nav.nav-pills
          - @user.skills.each  do |skill|
            %li.active
              = link_to("#{skill.name}", role_based_skill_path(skill), :class => "skill-level-#{@user.skill_level(skill).level}")
  %br
  %br
  - if @user_details.has_key?(:directreports)
    =# @user_details[:directreports].inspect
  - else
    =# "dont have any reporties #{@user_details[:title]}"
  =# @user_details.inspect
  - if is_user_profile?(@user)
    = link_to "Update Skills", skills_user_path(@user.id), :class => "btn btn-default"
    


          
    

app/views/users/show.html.haml
%p#notice= notice

.row
  .span1.text-right
    %b
      Name :
  .span3  
    = @user.name
.row
  .span1.text-right
    %b
      Email :
  .span3  
    = @user.email
    
        
.row
  .span1.text-right
    %b
      Skills :
  .span8
    %ul.nav.nav-pills
      - @user.skills.each  do |skill|
        %li.active
          = link_to("#{skill.name}(#{@user.skill_level(skill)})")
  


 

= link_to 'Edit', edit_user_path(@user), :class => "btn btn-primary"
\|
= link_to 'Back', users_path
\|
= link_to 'Add Skills', skills_user_path(@user)

app/views/users/skills.html.haml
- content_for :content_tab do      
  - Category.all.each_with_index do |category,i|
    %li
      %a{:href => "#section#{i}"}
        = category.name
          
- content_for :more_tab do           
  - Category.all.each_with_index do |category,i|
    - if ![0,1,2,3].include?(i)
      %li
        %a{:href => "#section#{i}"}
          = category.name
              
              
%p#notice= notice
%p
  %h3 Profile Info
%br
 
%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Skill last updated on:
  = @user.skillset_last_updated_on  
%br  
  = form_for @skill_set, :url => add_skills_user_path(@user) do |f|
    %h3 
      Update skills
    .row.top-bottom-buffer
      .span11.text-right
        %b
          Levels : 
          %i.skill-level-1
            1- No working knowledge
          |   
          %i.skill-level-2
            2 -Worked, but not extensively
          |          
          %i.skill-level-3
            3 - Have working knowledge
          |   
          %i.skill-level-4
            4 - Extensive Working Knowledge
          |  
          %i.skill-level-5
            5 - Expert/Specialist  
                    
    .tabbable.tabs-left
      %ul.nav.nav-tabs{:id => "myTab" }
        = yield(:content_tab)

          
    

 


      .tab-content
        - Category.all.each_with_index do |category,i|
          .tab-pane.fade{:id => "section#{i}"}
            - category.skills.each do |skill|
              .row.form-group
                - has_skill, skill_level = user_has_skill(@user,skill)
                .span2
                  = check_box_tag "skill_ids[]", skill.id, has_skill ? true : false , {:id=> "skillcheck_#{skill.id}", :class => "skill_check_box"}
                  - if has_skill
                    %span{:class => "skill-level-#{skill_level.level}"}
                      %b
                        = skill.name
                  - else
                    = skill.name
                .span2 
                  = check_box_tag "level_ids[]", has_skill ? skill_level.level : 1, has_skill ? true : false, :id => "level_#{skill.id}", :style=>"display:none" 
                  = select_tag( 'level[]',options_for_select([['1- No working knowledge', 1 ],['2 -Worked, but not extensively', 2 ],['3 - Have working knowledge', 3 ],['4 - Extensive Working Knowledge', 4 ], ['5 - Expert/Specialist', 5 ]], has_skill ? skill_level.level.to_s : ''), :id => "skill_#{skill.id}", :style => "width:150px;",:class => "skill_level")
                .span2
                  = has_skill ? "Last updated on : #{skill_level.created_at.strftime('%m/%d/%y')}" : ''
    %br 
    .row
      .span7.text-right
        = f.hidden_field :user_id, :value => @user.id
        = f.submit 'Update Skills', :class => "btn btn-primary"
      .span1  
        = link_to "Cancel", profile_user_path(@user.id), :class => "btn btn-primary"


:javascript
  $(document).ready(function(){ 
      var skill_level = new Array;
      $("#myTab a").click(function(e){
        e.preventDefault();
        $(this).tab('show');
      });
      $("#myTab li").first().addClass( "active" );
      $("#section0").addClass("in active");
      
      $(".skill_check_box").change(function(e){
        var level_id = this.id.split('_')[1];
        
        if($("#skillcheck_"+level_id).is(':checked'))
        {      
          $("#level_"+level_id).val($("#skill_"+level_id).val());
          $("#level_"+level_id).attr('checked', true);
        }
        else
        {
          $("#level_"+level_id).val(1);
          $("#level_"+level_id).attr('checked', false);
        }
      
      });
      
      $(".skill_level").change(function(e){
        var level_id = this.id.split('_')[1];      
        if($("#skillcheck_"+level_id).is(':checked'))
          {
            var level_value = this.value;
            $("#level_"+level_id).val(level_value);
            $("#level_"+level_id).attr('checked', true);
          }
      });
      

      
  });
:css
  h3{
    padding: 0 10px;
    margin-top: 20px;
    background: #F2F2F2;
  }
  .top-bottom-buffer { margin-top:20px; margin-bottom:20px; }  