config/routes.rb
ResourceMang1::Application.routes.draw do
  resources :users do
    member do
      get 'skills'
      post 'add_skills'
      get 'profile'
      get 'dashboard'
      get 'similar_skill'
      post 'user_search'
    end
    collection do
      post 'search'
    end
  end
  
  resources :skills
  resources :session do 
    collection do 
      get 'logout'
    end
  end

  resources :categories

  root :to => 'session#new'

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :description, :name, :category_id
  has_many :skill_sets, :class_name => "SkillSet"
  has_many :users, :through => :skill_sets
  belongs_to :category
end

app/controllers/skills_controller.rb
class SkillsController < InheritedResources::Base
    before_filter :authenticate_user
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.haml
= form_for @skill do |f|
  - if @skill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@skill.errors.count, "error")} prohibited this skill from being saved:"
      %ul
        - @skill.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :Category
    = f.select("category_id", Category.all.collect {|p| [ p.name, p.id ] })
  .form-group
    = f.label :name
    = f.text_field :name, :class => "form-control", :placeholder => "Name"
  .form-group
    = f.label :description
    = f.text_area :description, :class => "form-control", :placeholder => "Description", :rows => 6, :cols => 60
  .form-group
    = f.submit 'Save', :class => "btn btn-primary"

app/views/skills/edit.html.haml
%h3 Edit skill information

= render 'form'

app/views/skills/index.html.haml
%h3 Skills list

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Description
      %th Category
      %th Users
      %th
  %tbody
  - @skills.each do |skill|
    %tr
      %td= skill.name
      %td= truncate(skill.description, :length => 100, :separator => ' ')
      %td= skill.category.name
      %td= skill.users.count
      %td
        = link_to skill do
          %i.icon-eye-open
          Show
      %td
        = link_to edit_skill_path(skill) do
          %i.icon-pencil
          Edit
      %td
        = link_to skill, :method => :delete, :data => { :confirm => 'Are you sure?' } do
          %i.icon-trash
          Delete

%br

= link_to 'New Skill', new_skill_path, :class => "btn btn-primary"

app/views/skills/new.html.haml
%h3 New skill

= render 'form'

app/views/skills/show.html.haml
%p#notice= notice

.row
  %b Name:
  = @skill.name
%br  
.row
  %b Description:
  = @skill.description
%br  
%br  
.row
  %b Resources having skill : #{@skill.name}
.row
  %table.table.table-striped
    %thead
      %tr
        %th Employee ID 
        %th Name
        %th Email
    %tbody
    - @skill.users.each do |user|
      %tr
        %td= link_to( user.emp_id, profile_user_path(user))        
        %td= link_to( user.name, profile_user_path(user))
        %td= link_to(user.email, profile_user_path(user))
%br
.row    
  = link_to 'Edit Skill Information', edit_skill_path(@skill), :class => "btn btn-primary"