config/routes.rb
ResourceMang1::Application.routes.draw do
  resources :users do
    member do
      get 'skills'
      post 'add_skills'
      get 'profile'
      get 'dashboard'
      get 'similar_skill'
      post 'user_search'
    end
    collection do
      post 'search'
    end
  end
  
  resources :skills
  resources :session do 
    collection do 
      get 'logout'
    end
  end

  resources :categories

  root :to => 'session#new'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :skills
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  before_filter :authenticate_user


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this categorie from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label "Name"
    = f.text_field :name, :class => "form-control", :placeholder => "Name"
  .form-group
    = f.label "Description"
    = f.text_area :description, :class => "form-control", :placeholder => "Description", :rows => 6, :cols => 60
  .form-group
    = f.submit 'Save', :class => "btn btn-primary"

app/views/categories/edit.html.haml
%h3 Edit category

= render 'form'

app/views/categories/index.html.haml
%h3 Categories List

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Description
      %th Skills
      %th
      %th
  %tbody
  - @categories.each do |categorie|
    %tr
      %td= categorie.name
      %td= categorie.description
      %td= categorie.skills.count
      %td
        = link_to categorie do
          %i.icon-eye-open
          Show
      %td
        = link_to edit_category_path(categorie) do
          %i.icon-pencil
          Edit
           
      %td
        = link_to categorie, :method => :delete, :data => { :confirm => 'Are you sure?' } do
          %i.icon-trash
          Delete

%br

= link_to 'New categorie', new_category_path, :class => "btn btn-primary"

app/views/categories/new.html.haml
%h3 New categorie

= render 'form'

app/views/categories/show.html.haml
%p#notice= notice

.row
  %b Name:
  = @category.name
%br
.row
  %b Description:
  = @category.description
%br
%br

- @category.skills.each  do |skill|
  - if skill.users.size != 0
    .row
      Resources with skill:
      %b
        = skill.name
      %table.table.table-striped
        %thead
          %tr
            %th Employee ID            
            %th Name
            %th Email
        %tbody
        - skill.users.each do |user|
          %tr
            %td= link_to( user.emp_id, profile_user_path(user))
            %td= link_to( user.name, profile_user_path(user))
            %td= link_to(user.email, profile_user_path(user))


.row
  = link_to 'Edit category Information', edit_category_path(@category), :class => "btn btn-primary"