config/routes.rb
ResourceMang1::Application.routes.draw do
  resources :users do
    member do
      get 'skills'
      post 'add_skills'
      get 'profile'
      get 'dashboard'
      get 'similar_skill'
      post 'user_search'
    end
    collection do
      post 'search'
    end
  end
  
  resources :skills
  resources :session do 
    collection do 
      get 'logout'
    end
  end

  resources :categories

  root :to => 'session#new'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Skills Management
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href: ""} Skill Management
          - if logged_in?
            .nav-collapse
              %ul.nav
                - if is_admin?      
                  %li
                    = link_to skills_path do
                      %i.icon-retweet
                      Browse Skills  
                - if is_admin? 
                  %li
                    = link_to  categories_path do
                      %i.icon-adjust
                      Browse Categories
                - if is_admin? 
                  %li
                    = link_to users_path do
                      %i.icon-asterisk
                      Users
                - if session[:user]
                  %li
                    = link_to  profile_user_path(session[:user].id)  do
                      %i.icon-home
                      My Profile
                - if session[:user]
                  %li
                    = link_to  skills_user_path(session[:user].id)  do
                      %i.icon-gift
                      Update My Skills
                  %li
                    = link_to dashboard_user_path(session[:user].id) do
                      %i.icon-user
                      CI People
                  %li
                    = link_to logout_session_index_path do
                      %i.icon-lock
                      Logout
    .container
      .row
        .span12= yield
    #footer
      .container
        %p.text-muted
          